# Build image
# `docker-compose -f docker-compose.yml build`
# Push to registry
# `docker-compose -f docker-compose.yml push`

version: '3.8'

services:

  hdc-integration-tests:
    image: registry.lts.harvard.edu/lts/hdc-integration-tests:0.0.1
    build:
      context: .
      dockerfile: Dockerfile