# Start: `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`
# Stop: `docker-compose -f docker-compose-local.yml stop`

version: '3.8'

services:

  hdc-integration-tests:
    container_name: 'hdc-integration-tests'
    build:
      context: './'
      dockerfile: 'DockerfileLocal'
    volumes:
      - './:/home/appuser'
    env_file:
      - '.env'
    ports:
      - '10582:8443'
    networks:
      - drsts-net

networks:
  drsts-net:
    name: "drsts-net"